//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public string BuildingID { get; set; }
        public string UserID { get; set; }
        public string BuildingName { get; set; }
        public string Address1 { get; set; }
        public string Street { get; set; }
        public string TownArea { get; set; }
        public Nullable<System.DateTime> DateSurveyed { get; set; }
    
        public virtual User User { get; set; }
    }
}
